cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove')
]

search_app/urls.py
from django.urls import path
from .views import SearchResultsListView

app_name = 'search_app'

urlpatterns = [
    path('', SearchResultsListView.as_view(), name='searchResult'),
]

shop/urls.py
from django.urls import path
from .views import ProdCat, ProdDetail

app_name = 'shop'

urlpatterns = [
    path('', ProdCat.as_view(), name = 'allProdCat'),
    path('<uuid:category_id>/', ProdCat.as_view(), name = 'products_by_category'),
    path('<uuid:category_id>/<uuid:product_id>/', ProdDetail.as_view(), name = 'prod_detail'),
]

shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('',include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
import uuid
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    id = models.UUIDField(
        primary_key = True,
        default = uuid.uuid4,
        editable = False)
        
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)


    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('shop:products_by_category', args=[self.id])
    
    def __str__(self):
        return self.name

class Product(models.Model):
    id = models.UUIDField(
        primary_key = True,
        default = uuid.uuid4,
        editable = False)

    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete = models.CASCADE)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    updated = models.DateTimeField(auto_now=True,blank=True,null=True)


    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_absolute_url(self):
        return reverse('shop:prod_detail', args=[self.category.id, self.id])

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator, EmptyPage, InvalidPage

# Create your views here.

class ProdCat(ListView):
    model = Product

    def get(self, request, category_id=None):
        category = None
        products = None
        if category_id != None:
            category = get_object_or_404(Category, id = category_id)
            products = Product.objects.filter(category = category, available = True)
        else:
            products = Product.objects.all().filter(available=True)
        
        '''Pagination Code'''
        paginator = Paginator(products, 6)
        try:
            page = int(request.GET.get('page', '1'))
        except:
            page = 1
        try:
            products = paginator.page(page)
        except (EmptyPage, InvalidPage):
            products = paginator.page(paginator.num_pages)

        return render(request,"shop/category.html",{'category':category, 'products':products})


class ProdDetail(DetailView):
    model = Product

    def get(self, request, category_id, product_id):
            try:
                product = Product.objects.get(category_id = category_id, id = product_id)
            except Exception as e:
                raise e

            return render(request,"shop/product.html",{'product':product})

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
    crossorigin="anonymous">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        <div class="container-fluid bg-light navbar-fixed-top my_top_navbar_div">
            {% include 'top-navbar.html' %}
        </div>
        {% include 'header.html' %}
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}

        {% include 'footer.html' %}
    </div>
    <!-- Separate Popper and Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"crossorigin="anonymous"></script>
</body>
</html>

shop/templates/footer.html
<div class = "footer navbar-fixed-bottom my-footer">
    <p class = "text-center">&copy; Online Cushions. All Rights Reserved.</p>
    </div>

shop/templates/header.html
{% load static %}
<header>
    <div style="text-align: center;">
        <a href="{% url 'shop:allProdCat' %}"><img src="{% static 'images/logo.png' %}" alt="Online Cushion Store"></a>
    </div>
</header>

shop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bstarget="#navbarSupportedContent" aria-controls="navbarSupportedContent" ariaexpanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" databs-toggle="dropdown" aria-expanded="false">
        Shop
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_absolute_url}}">{{cat.name}}</a></li>
            {% endfor %}
        </ul>
    </li>
    {% if item_count > 0 %}
    <li class="nav-item">
    <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{item_count}})</a>
    </li>
    {% endif %}
    </ul>
    <form class="d-flex" action="{% url 'search_app:searchResult' %}" method="get">
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
    </div>
    </div>
    </nav>

<!---->
<nav>
    <ul>
        <li><a href="{% url 'shop:allProdCat' %}">All Products</a></li>
        {% for cat in links %}
            <a href = "{{cat.get_absolute_url}}"> {{cat.name}}</a>
            <br>
        {% endfor %}
        <li>Your Cart</li>
    </ul>
</nav>
<!---->

shop/templates/search.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
We have a variety of stunning and comfy cushions. Look for the one that suits your needs.
{% endblock %}
{% block title %}
Search - Perfect Cushion Store
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for: <b>"{{ query}}"</b></p>
</div>
<div class="container">
    <div class="row mx-auto">
        {% for product in product_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md12 col-lg-4">
            <div class="card text-center" style="min-width: 18rem;">
                <a href="{{product.get_absolute_url}}"><img class="card-img-top my_image" src="{{product.image.url}}"
                        alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>€{{product.price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 results found.</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

shop/templates/top-navbar.html
<div class="container">
    <div class="my_custom_menu">
    <ul>
    {% if user.is_authenticated %}
    <li>
     Welcome, <a href="#" class="dropdown-toggle" data-bs-toggle="dropdown"
     aria-haspopup="true" aria-expanded="false">{{ user.username }}
    <i class="fas fa-user-circle"></i></a>
    </li>
    <li>
    <a href="{% url 'signout' %}">Sign Out <i class="fas fa-sign-out-alt"></i></a>
    </li>
    {% else %}
    <li>
    <a href="{% url 'signup' %}">Sign Up <i class="fas fa-user-plus"></i></a>
    </li>
    <li>
    <a href="{% url 'signin' %}">Sign In <i class="fas fa-sign-in-alt"></i></a>
    </li>
    {% endif %}
    </ul>
    </div>
    </div>